version: '3.8'

services:
  # Servicio PHP-FPM
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-php
    volumes:
      - .:/var/www/html
    networks:
      - laravel-network

  # Servicio Nginx
  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    ports:
      - "8000:80"
    networks:
      - laravel-network

# Red compartida por todos los servicios
networks:
  laravel-network:
    driver: bridge
